version: "3"

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge

services:
  backend:
    image: "kpd-backend"
    container_name: "kpd-backend"
    build:
      context: backend #имя папки где лежит наш докер файл
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "4000:3001" #локальный 3001 доступен снаружи по 4000
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - internal-network
      - internet
  frontend:
    image: "kpd-frontend"
    container_name: "kpd-frontend"
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - backend
    restart: always
    ports:
      - "8080:80"
  postgres:
    image: postgres:12.12-alpine
    container_name: "postgres"
    env_file: .env
    networks:
      - internal-network
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres

    #порты наружу для дб в целях безрпасности не указывают
